### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [DSH105/Nexus#101]
Hi
The following lines have cryptographic API misuses. <br> File name => nexu-https-plugin/src/main/java/lu/nowina/nexu/https/HttpsPlugin.java: Line number => 191: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => nexu-https-plugin/src/main/java/lu/nowina/nexu/https/JettyHttpsServer.java: Line number => 70: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => nexu-https-plugin/src/main/java/lu/nowina/nexu/https/HttpsPlugin.java: Line number => 196: API name => KeyStore:<BR> File name => nexu-https-plugin/src/main/java/lu/nowina/nexu/https/HttpsPlugin.java: Line number => 168: API name => KeyStore:Unexpected call to method store on object of type java.security.KeyStore. Expect a call to one of the following methods getKey,getEntry<BR> File name => nexu-https-plugin/src/main/java/lu/nowina/nexu/https/HttpsPlugin.java: Line number => 218: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by lol768** [comment]
I .. am not sure these issues at all relate to this repository.
